name: CI

env:
  ZIG_VERSION: "0.15.2"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Install Zig 0.15.2
        run: bash .github/scripts/install-zig.sh "${ZIG_VERSION}"

      - name: non-blocking test
        run: zig build test -Dforce_blocking=false
      - name: blocking test
        run: zig build test -Dforce_blocking=true
      - name: build server x86-linux-gnu
        run: cd support/autobahn/server && zig build -Dtarget=x86-linux-gnu
      - name: build server x86_64-linux-gnu
        run: cd support/autobahn/server && zig build -Dtarget=x86_64-linux-gnu
      - name: build server x86_64-windows-gnu
        run: cd support/autobahn/server && zig build -Dtarget=x86_64-windows-gnu
      - name: build client x86-linux-gnu
        run: cd support/autobahn/client && zig build -Dtarget=x86-linux-gnu
      - name: build server x86_64-linux-gnu
        run: cd support/autobahn/client && zig build -Dtarget=x86_64-linux-gnu
      - name: build clietn x86_64-windows-gnu
        run: cd support/autobahn/client && zig build -Dtarget=x86_64-windows-gnu
